language: java
jdk:
  - oraclejdk8
sudo: required
dist: trusty
addons:
  sonarqube:
    organization: apsodlkqweivwlkwbf
    token:
      secure: NCfP12i0DzrKIecX5BcDgki2MUhdIsHmeGX+5JZZxziKf2v/w95C73bBuc4z0utSVlaM534Do1TeXmofcQWk20OCgPAE/Xi5XVi10nQois0rAK+PtB9GVHZ3eJcsYtInOSemp4lf4c93JAwsGzKiqsiw6TOOF5vUJukTDZYchgEYu4aFVWOkBFY32zeB+L0VytqU6pplB2TpTppohE6Wx0XDQNOn2Jc4Oe2ri/aIHDOareZaET6TcWXWjHdX91w13W+AeyFH/gyewpRoCoq3ZaPxxL5T63ot0sHXYScZq3WrXcC37NQBKdD19m+49fTrQxQ2zcrXkxVGFYGaHsxt+HrlRIOrwWLh9qZ4mY8uxDKhL2TK05vzw347AHW3So3vgLp5hR3f3j/AQJ4woy2u4/4zE6hRICkWdm8LcJRq7DauUowXic6z54QEwJ8zhabhjdLsM1ZtNCRxwkM9AVD9NBCQVtFPfrFdWJRolz9pThKdx6SlMQJ91EQcC1q6+PhYMW08I14AiLinxT5R+FycEpvA/lONQPZifOVyLe9U4jqvKGNa6iB+TZXJ2urxlY05MHls0IsJciJYDBsuN2JzESH6DttGxBmrEG6VItYJCX6WpXwNSVpE6s9CUEw5R1FSwVNP9Ev1Fb/AmG8e6dL18z+XMcJxOKRcpLhOQT6nsQ4=

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar